### ISSUE TITLE
bug: TypeError: Cannot read properties of null (reading 'displayName')

### ISSUE THREAD

**Issue by iuioiua** [denoland/saaskit#196]
```ts
An error occurred during route handling or page rendering. TypeError: Cannot read properties of null (reading 'displayName')
    at getUserDisplayName (file:///src/utils/db.ts:276:15)
    at Object.ItemSummary (file:///src/components/ItemSummary.tsx:42:12)
    at https://esm.sh/v120/preact-render-to-string@5.2.6/X-ZS8q/deno/preact-render-to-string.mjs:12:1830
    at T (https://esm.sh/v120/preact-render-to-string@5.2.6/X-ZS8q/deno/preact-render-to-string.mjs:12:1857)
    at T (https://esm.sh/v120/preact-render-to-string@5.2.6/X-ZS8q/deno/preact-render-to-string.mjs:12:2844)
    at T (https://esm.sh/v120/preact-render-to-string@5.2.6/X-ZS8q/deno/preact-render-to-string.mjs:12:2844)
    at T (https://esm.sh/v120/preact-render-to-string@5.2.6/X-ZS8q/deno/preact-render-to-string.mjs:12:1933)
    at T (https://esm.sh/v120/preact-render-to-string@5.2.6/X-ZS8q/deno/preact-render-to-string.mjs:12:1074)
    at T (https://esm.sh/v120/preact-render-to-string@5.2.6/X-ZS8q/deno/preact-render-to-string.mjs:12:1933)
    at T (https://esm.sh/v120/preact-render-to-string@5.2.6/X-ZS8q/deno/preact-render-to-string.mjs:12:1933)
```

**Comment by iuioiua** [comment]
This is no longer an issue since #192.
