### ISSUE TITLE
Bug report "500 internal error: Cannot read properties of undefined (reading 'login')"

### ISSUE THREAD

**Issue by irekgroup** [denoland/saaskit#484]
**Describe the bug** 
Server error
500 internal error: Cannot read properties of undefined (reading 'login')

```
An error occurred during route handling or page rendering. TypeError: Cannot read properties of undefined (reading 'login')
    at AccountPage (file:///C:/Users/name/Favorites/saaskit-main/routes/index.tsx:42:23)
    at render (https://deno.land/x/fresh@1.4.2/src/server/render.ts:216:25)
    at https://deno.land/x/fresh@1.4.2/src/server/context.ts:790:30
    at handler.GET (https://deno.land/x/fresh@1.4.2/src/server/context.ts:269:47)
    at routes.<computed>.methods.<computed> (https://deno.land/x/fresh@1.4.2/src/server/context.ts:857:13)
    at handler (https://deno.land/x/fresh@1.4.2/src/server/router.ts:197:30)
    at Object.next (https://deno.land/x/fresh@1.4.2/src/server/context.ts:573:36)
    at recordVisit (file:///C:/Users/allab/Favorites/saaskit-main/routes/_middleware.ts:48:20)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async setState (file:///C:/Users/name/Favorites/saaskit-main/routes/_middleware.ts:38:10)
```

**To Reproduce** Steps to reproduce the behavior:

I start the server in two ways:
1. deno task start
2. via docker

In two cases I get this error, in the case of deno task start I additionally get the error `STRIPE_SECRET_KEY` environment variable is not defined. Stripe is disabled.

**Expected behavior** 
Ultimately I want to run the saaskit-main version

**Screenshots** 
![image](https://github.com/denoland/saaskit/assets/70753735/41b81505-a58f-43a7-854d-941a9c557e33)

**Desktop (please complete the following information):**

- OS: win10, 64bit
- Browser [chrome]

**Additional context** 
I just followed the instructions in the saaskit-main repository, adding all the keys where needed, and in the end I can not start the server.

**Comment by iuioiua** [comment]
Are you able to provide further details? I'm unable to reproduce the issue. Perhaps, you could try running `deno task db:reset` then `deno task db:seed`.

**Comment by iuioiua** [comment]
Gentle ping @irekgroup

**Comment by irekgroup** [comment]
> Нежный пинг@irekgroup

I just followed the instructions for main-saaskit and got this error upon startup

**Comment by iuioiua** [comment]
Please try adding `--reload` to the `start` task defined in the `deno.json` file.

**Comment by irekgroup** [comment]
```
Task start deno run --unstable -A --watch=static/,routes/ dev.ts --reload
Watcher Process started.
`STRIPE_SECRET_KEY` environment variable is not defined. Stripe is disabled.
The manifest has been generated for 34 routes and 6 islands.

 🍋 Fresh ready 
    Local: http://localhost:8001/

An error occurred during route handling or page rendering. TypeError: Cannot read properties of undefined (reading 'login')
    at AccountPage (file:///C:/Users/allab/Favorites/saaskit-main/routes/index.tsx:42:23) 
    at render (https://deno.land/x/fresh@1.4.3/src/server/render.ts:216:25)
    at https://deno.land/x/fresh@1.4.3/src/server/context.ts:794:30
    at handler.GET (https://deno.land/x/fresh@1.4.3/src/server/context.ts:273:47)
    at routes.<computed>.methods.<computed> (https://deno.land/x/fresh@1.4.3/src/server/context.ts:861:13)
    at handler (https://deno.land/x/fresh@1.4.3/src/server/router.ts:197:30)
    at Object.next (https://deno.land/x/fresh@1.4.3/src/server/context.ts:577:36)
    at recordVisit (file:///C:/Users/allab/Favorites/saaskit-main/routes/_middleware.ts:48:20)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async setState (file:///C:/Users/allab/Favorites/saaskit-main/routes/_middleware.ts:38:10)
```

**Comment by roberto-morado** [comment]
Hello @irekgroup,

I recall encountering a similar error when I initially cloned the repository. It was due to a minor configuration issue on my end, though I can't quite recall the exact steps I took to resolve it. However, I've made several attempts to reproduce the error without success.

In the current main branch (3a193e16ed3a554d46cafca8eecb8bc0a459a66a), you should be able to start using Deno Saaskit with just three simple commands (technically one):

```sh
$ git clone https://github.com/denoland/saaskit
$ cd saaskit
$ deno task start
```

I've tested this on Windows, Linux, and MacOS, using a variety of browsers including Chrome, Firefox, Chromium, Firefox Developer Edition, DuckDuckGo Browser, Waterfox, Safari, and Edge—all running the latest versions.

You should be good to go with these instructions. 👍

**Comment by iuioiua** [comment]
@irekgroup, we've made numerous simplifications in the last week, reducing the possibilities of failure. Could you please update and try again? Also, please ensure you're running the latest version of Deno.

**Comment by iuioiua** [comment]
Hi @irekgroup, just following up. Are you still encountering issues after updating?

**Comment by iuioiua** [comment]
Closing as stale.
