### ISSUE TITLE
Bug report: `formatCurrency()` returns wrong format for `de-DE` as `naviator.language`

### ISSUE THREAD

**Issue by niklasmtj** [denoland/saaskit#631]
**Describe the bug** A clear and concise description of what the bug is.

The `formatCurrency()` test is failing on a computer with `navigator.language` set to `de-DE`.  

```
[display] formatCurrency() => ./utils/display_test.ts:34:6
error: AssertionError: Values are not equal.


    [Diff] Actual / Expected


-   5$
+   $5


  throw new AssertionError(message);
        ^
    at assertEquals (https://deno.land/std@0.202.0/assert/assert_equals.ts:53:9)
    at file:///Users/<user>/saaskit/utils/display_test.ts:35:3
```

**To Reproduce** Steps to reproduce the behavior:

Run `deno task test` with the `navigator.language` set to `de-DE` for example.

**Expected behavior** A clear and concise description of what you expected to
happen.

Having the expected correct `$` format however the `navigator.language`. 

**Additional context** Add any other context about the problem here.

This might be an interesting case since for example `€` is handled the other way. There it would be `5€` and not `€5`

**Comment by niklasmtj** [comment]
After diving deeper into the [documentation of `Intl.NumberFormat`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/format) this is the indended behaviour. However we then have to adapt our tests. Since `navigator.language` is a constant and read-only we can not just set it to `en-US` when running the tests.
